### ISSUE TITLE
VideoStream error on last version

### ISSUE THREAD

**Issue by tentone** [tentone/nunuStudio#420]
@helzapps

One other issue is in our script we are doing something like so:
```
    var vs = new VideoStream(
      "./videos/SIRTeX_IllustratedMoGraph_Update_v06_noAudio.mp4"
    );
    if (vs != null) {
      var texture = new VideoTexture(vs);
      ...
    }
```
The null test worked in version 0.97.14 and would bypass actually trying to create the video texture in our editor running. But now in 0.98.5 and today's 0.98.6 that test is failing in that even though that file isn't local in our test runs, the `vs` var is not null and it's attempting to create the `VideoTexture` but then it throws an error (first screen shot in my description). Should this be coded differently or in fact is there a separate bug that should be reported for this issue now? Thanks?

**Comment by tentone** [comment]
```
This is a bit weird that vs variable should never be null in any situation.

Can you please show what error you are getting when accessing the VideoStream?
```

**Comment by helzapps** [comment]
<img width="983" alt="Screen Shot 2020-07-23 at 4 22 55 PM" src="https://user-images.githubusercontent.com/1172574/88347890-c65e8a00-cd00-11ea-8556-2bc911770902.png">
If I console.log out the VS object it is now printing:

```vs = {"name":"video","uuid":"3C575387-B7C8-4C17-A261-9A61C6358895","type":"Video","format":"url","encoding":"mp4","data":"./videos/SIRTeX_IllustratedMoGraph_Update_v06_noAudio.mp4"}```

It's possible that previously it wasn't null and had this same JSON object, but the data property wasn't null that it's trying to read.

**Comment by helzapps** [comment]
To be clear, the video assets are located in the web project in which we are embedding our nunu scene.

**Comment by helzapps** [comment]
More info: 
If I take your Video Tutorial project and attempt to load and run it, then I get this error:
<img width="446" alt="Screen Shot 2020-07-23 at 4 40 31 PM" src="https://user-images.githubusercontent.com/1172574/88348790-3a9a2d00-cd03-11ea-9fb8-0ce776005e6b.png">

The main difference is you are loading yours in the `initialize()` function. If I move it into a function like how we are doing it (which I don't know why we are doing it this way...) then I get the same error:

`
var videosLoaded = false;

function initialize()
{
	
}

function loadVideo()
{
	var texture = new VideoTexture(new VideoStream("https://nunustudio.org/learn/basics/17_video/sample.mp4"));
	var material = program.getMaterialByName("default");
	material.emissiveMap = texture;
	material.emissive.setHex(0xFFFFFF);
}


function update(delta)
{
	if (!videosLoaded) {
		videosLoaded = true;
		loadVideo();
	}
}
`
Then I get the same error as in our project where it cannot read property of `data` of null.

**Comment by helzapps** [comment]
So this error persists in the latest version 0.98.7, but something else wrong or this is still related. I cannot create new video textures. I tried creating a super simple scene with three boxes with planes associated with them. To then created three standard materials as is suggested for dynamically loading a video texture. I then assigned them to the three planes in the project explorer. When I publish for web and run, I get a TON of WebGL errors:

```
[.WebGL-0x7fdf0400a200]RENDER WARNING: texture bound to texture unit 0 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
WebGL: INVALID_VALUE: tex(Sub)Image2D: video visible size is empty
...
```

**Comment by tentone** [comment]
Hello

Thanks a lot for the additional information i think that i have figured out what is wrong with the video texture.

That second render warning should be while rendering with the texture still uploading.

Thanks a lot once. Working on it.

**Comment by tentone** [comment]
This bug should be fixed now in the version 0.98.8, 

Thanks a lot for reporting this issue.

**Comment by helzapps** [comment]
While I no longer get the scripting error from the editor, I am still getting the errors mentioned in this comment: https://github.com/tentone/nunuStudio/issues/420#issuecomment-663749707

Opening a new issue.
